---
title: "README"
output: 
  html_document:
    keep_md: true
---
```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DT)
library(dplyr)
library(plotly)
library(rmarkdown)
library(ggmap)
library(ggplot2)
library(raster)
library(rgeos)
library(maptools)
library(rgdal)
library(readAny)
library(leaflet)
library(tidyverse)
library(readr)
library(ROCR)
library(PerformanceAnalytics)
library(e1071)
library(caret)
library(gbm)
library(corrplot)
library(ggcorrplot)
library(MASS)
library(rpart)
library(caTools)
library(naivebayes)
library(class)
library(ISLR)
library(glmnet)
library(Hmisc)
library(funModeling)
library(pROC)
library(randomForest)
library(klaR)
library(scales)
library(cluster)
library(factoextra)
library(DataExplorer)
library(ClustOfVar)
library(GGally)


```

## 데이터 불러오기

S-Dot 1시간 측정 평균값이 저장된 csv파일 read
```{r }
#분석하고자 하는 csv데이터를 sdot이라는 데이터 프레임에 넣기 
sdot<-read.csv("data/sdot_20200507.csv", fileEncoding = 'euc-kr', head=TRUE, check.names=FALSE) 

```

```{r, layout="l-body-outset"}
#데이터 중 위에서부터 10개의 데이터만 확인
sdot %>% head(10)
```



sdot에 저장된 값에 대한 데이터 요약 
```{r }
#명령어 summary(데이터프레임)
summary(sdot) 
```
위의 값을 확인 했을때 현재 살펴보고자 하는 미세먼지, 초미세먼지 결측값, 음수, 0값을 제거 

```{r }
# 분석 편의상 컬럼 이름 변경 
sdot <- sdot %>% dplyr::rename(super_dust =`초미세먼지 보정 (㎍/㎥)`)
sdot <- sdot %>% dplyr::rename(dust =`미세먼지 보정 (㎍/㎥)`)
sdot <- sdot %>% dplyr::rename(model =시리얼)
sdot <- sdot %>% dplyr::rename(temp =`기온 (℃)`)
sdot <- sdot %>% dplyr::rename(습도 =`상대습도 (%)`)
sdot <- sdot %>% dplyr::rename(lux =`조도 (lux)`)
sdot <- sdot %>% dplyr::rename(db =`소음 (dB)`)


#사용하고자 하는 컬럼 선택 
sdot <- sdot %>% dplyr::select(model, date, hour, dust,super_dust,temp,습도, lux, db)

# 결측값 확인 
plot_missing(sdot)
```

```{r }
#미세먼지 값이 0이하 or 초미세먼지 값이 0 이하 값 제거
sdot <-sdot %>% filter(!super_dust <=0 , !dust <=0)

#명령어 summary(데이터프레임)로 미세먼지 보정, 초미세먼지 보정 값 재확인 
summary(sdot) 
#결측값 및 0이하 값 제거 확인
```

```{r, warning= FALSE, message=F }
#시간에 따른 미세먼지 값 확인 
#동적 그래프 생성규칙 

#plot_ly(데이터프레임, x = ~시간, y = ~값)
# plot_ly(sdot, x = ~hour, y = ~dust, name = 'trace 0', type = 'scatter', mode = 'markers',
#         marker = list(opacity = 0.4, color = "blue"))
# 
# plot_ly(sdot, x = ~hour, y = ~super_dust, name = 'trace 0', type = 'scatter', mode = 'markers',
#         marker = list(opacity = 0.4, color = "red"))

cor_heart <- cor(sdot[,3:8])


corrplot(cor_heart, method = "ellipse", type="upper",)
```

```{r, warning= FALSE, message=F }
ggcorrplot(cor_heart,lab = T)

```
```{r, warning= FALSE, message=F }
ggcorr(cor_heart, label = T, label_round = 2)

```

```{r, warning= FALSE, message=F }
#센서 설치정보 불러오기 
 model <- read.csv("data/model.csv", head = TRUE, fileEncoding = 'euc-kr')
# 
# model$y<- rnorm(n=851, mean=126.981, sd=0.08446877)
# model$x<- rnorm(n=851, mean=37.54613, sd=0.05030271)
# write.csv(model,"model.csv", fileEncoding = 'euc-kr')

#SDot 데이터와 설치 정보 결합하기 
sdot_model <- merge(sdot, model, by ="model", all.x = TRUE)

#경도 위도 이름 변경 및 사용데이터 결합
sdot_model <- sdot_model %>% dplyr::rename(long = y, lat = x)
sdot_model <- sdot_model %>% group_by(gover, model, hour) %>% summarise(long = mean(long), lat = mean(lat), super_dust = mean(super_dust), dust = mean(dust), temp = mean(temp), 습도=mean(습도), lux = mean(lux), db= mean(db))

```

## 지도 데이터 불러오기 
지도정보 불러오기 :  
```{r, warning= FALSE, message=F }
#서울시/자치구/이름 파일 
p<- read.any("data/sample.csv", header = TRUE) #시각화할 데이터셋

#대한민국 시군구 행정구역 shp파일 
map =readOGR('data/TL_SCCO_SIG.shp',encoding = 'cp949')

#행정구역 shp 전처리
map <- spTransform(map, CRSobj = CRS('+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs'))
map@polygons[[1]]@Polygons[[1]]@coords %>% head(n = 10L)
new_map <- fortify(map, region = 'SIG_CD')
new_map$id <- as.numeric(new_map$id)

#대한민국 시군구 행정구역 중 서울시만 불러오기 
seoul_map <- new_map[new_map$id <= 11740,]

#서울시 자치구 이름 표기 정보 결합
P_merge <- merge(seoul_map, p, by='id')
P_merge <- P_merge %>% dplyr::rename(gover = 시군구명)

top_stat_sdot<-sdot_model %>% group_by(gover, hour) %>% summarise(dust = mean(dust), super_dust = mean(super_dust), temp = mean(temp), 습도=mean(습도), lux = mean(lux), db= mean(db))

top_merge<-merge(P_merge, top_stat_sdot, by="gover", all.x =TRUE)


################### 경계그룹 ##############################
split_data_poly = lapply(unique(P_merge$group), function(x) {
  df = as.matrix(P_merge[P_merge$group == x, c("long", "lat")])
  polys = Polygons(list(Polygon(df)), ID = x)
  return(polys)
})

#split_data_poly
data_polys = SpatialPolygons(split_data_poly)



```

## 데이터
```{r, warning= FALSE, message=F }
ggplot(top_stat_sdot, aes(x = hour, y = dust, color = gover))+
  geom_smooth(se = FALSE) +
    theme(text=element_text(family="NanumGothic"))
```

```{r, warning= FALSE, message=F }
ggplot(top_stat_sdot, aes(x = hour, y = super_dust, color = gover))+
  geom_smooth(se = FALSE) +
    theme(text=element_text(family="NanumGothic"))
```

```{r, warning= FALSE, message=F }
ggplot(top_stat_sdot, aes(x = hour, y = 습도, color = gover))+
  geom_smooth(se = FALSE) +
    theme(text=element_text(family="NanumGothic"))
```

```{r, warning= FALSE, message=F }
ggplot(top_stat_sdot, aes(x = hour, y = temp, color = gover))+
  geom_smooth(se = FALSE) +
    theme(text=element_text(family="NanumGothic"))
```

```{r, warning= FALSE, message=F }
ggplot(top_stat_sdot, aes(x = hour, y = lux, color = gover))+
  geom_smooth(se = FALSE) +
    theme(text=element_text(family="NanumGothic"))
```


```{r, warning= FALSE, message=F }
ggplot(top_stat_sdot, aes(x = hour, y = db, color = gover))+
  geom_smooth(se = FALSE) +
    theme(text=element_text(family="NanumGothic"))
```


```{r, warning= FALSE, message=F }
test <- sdot_model[6:11]
test2 <- sdot_model[1]
sdot_model2 <- bind_cols(test2,test)



sdot_model3<-sdot_model2[duplicated(sdot_model2$gover),]



#row.names(sdot_model2) <- sdot_model2$gover2

```


```{r, warning= FALSE, message=F }
pgdata2 <- sdot_model %>% group_by(gover) %>%  summarise_all(list(mean = mean ))
pgdata2 <- pgdata2 %>% filter(!gover =='대기측정소')
pgdata2$hour_mean <-NULL
pgdata2$lat_mean <-NULL
pgdata2$long_mean <-NULL
pgdata2$model_mean <-NULL

worldcup2 <- pgdata2

num_df <- worldcup2

result <- num_df[-1]
row.names(result) <- num_df$gover
num_df <- result


apply(num_df, 2, var)


#주성분 분석
worldcup_pca <- prcomp(num_df, scale = TRUE)
summary(worldcup_pca)
#첫번째 주성분(PC1)의 누적 기여율은 0.3585, 즉 35%에 해당함.
#PC1이 분석대상의 데이터가 가지고 있던 정보가 PC1 주성분에 집약되어 있는 크기를 설명함

```

```{r, warning= FALSE, message=F }

screeplot(worldcup_pca, main = "", col = "green", type = "lines", pch = 1, npcs = length(worldcup_pca$sdev))
#요약과 그래프를 통해서 알 수 있듯이 PC1 + PC2 + PC3의 누적 기여율은 0.88 즉, 약 88%가 되며 성분 선택은 PC1,PC2,PC3까지만 하면 됨


```

```{r, warning= FALSE, message=F }
# 각각에 대한 제1주성분, 제2주성분 점수 구하기
round(predict(worldcup_pca), 3)


worldcup_pca$rotation <- -worldcup_pca$rotation
worldcup_pca$x <- -worldcup_pca$x
biplot(worldcup_pca)

biplot(worldcup_pca, cex = 0.8, choices = c(1,3)) 

```


```{r, warning= FALSE, message=F }

#지도에 SDOT 설치 정보 뿌리기
# library(mapview)
# m <-leaflet(data_polys) %>%
#   setView(lng=126.9784, lat=37.566, zoom=11) %>%
#   addPolygons(fillColor = "white",weight ="2",color = "black", opacity = 0.8   ) %>% 
#   addProviderTiles('CartoDB.Positron') %>% 
#   addCircleMarkers(data = sdot_model, lng=~long, lat=~lat, color="#20639B", radius = "2",stroke = TRUE, fillOpacity = 0.8, weight =1)
# 
# mapshot(m, file = "map1.png")

```

```{r, warning= FALSE, message=F }

# 미세먼지 값 표시하기
# 미세먼지 범례설정 

# sdot_model$dust_range <- cut(sdot_model$dust, 
#                              c(0,30,80,150,999), include.lowest = T,
#                              labels = c('0','15','35','75'))
# colors_sdot <- c("#3982BA", "#66B74F", "#FAE284", "#E93A30")
# dust_color_sdot <- colorFactor(palette = colors_sdot , sdot_model$dust_range)
# 
# 
# # 초미세먼지 범례설정
# sdot_model$super_dust_range <- cut(sdot_model$super_dust, 
#                              c(0,15,35,75,999), include.lowest = T,
#                              labels = c('0','15','35','75'))
# colors_sdot <- c("#3982BA", "#66B74F", "#FAE284", "#E93A30")
# super_dust_color_sdot <- colorFactor(palette = colors_sdot , sdot_model$super_dust_range)
# 
# 
# 
# # 일별 
# mean_sdot_model <- sdot_model %>% group_by(model) %>% summarise(super_dust =mean(super_dust), dust = mean(dust), long = mean(long), lat = mean(lat))
# 
# # 일별 미세먼지 범례설정 
# mean_sdot_model$dust_range <- cut(mean_sdot_model$dust, 
#                              c(0,30,80,150,999), include.lowest = T,
#                              labels = c('0','15','35','75'))
# colors_sdot <- c("#3982BA", "#66B74F", "#FAE284", "#E93A30")
# dust_color_sdot <- colorFactor(palette = colors_sdot , mean_sdot_model$dust_range)
# 
# 
# # 일별 초미세먼지 범례설정
# mean_sdot_model$super_dust_range <- cut(mean_sdot_model$super_dust, 
#                              c(0,15,35,75,999), include.lowest = T,
#                              labels = c('0','15','35','75'))
# colors_sdot <- c("#3982BA", "#66B74F", "#FAE284", "#E93A30")
# super_dust_color_sdot <- colorFactor(palette = colors_sdot , mean_sdot_model$super_dust_range)
# 
# 
# #미세먼지 농도 지도에 표기하기
# leaflet(data_polys) %>%
#   setView(lng=126.9784, lat=37.566, zoom=11) %>%
#   addPolygons(fillColor = "white",weight ="2",color = "black", opacity = 0.8  ) %>%
#   addProviderTiles('CartoDB.Positron') %>%
#   addCircleMarkers(data = mean_sdot_model, lat = ~lat, lng = ~long,
#                    color = ~dust_color_sdot(dust_range), popup = sdot_model$dust,
#                    radius = ~sqrt(dust/3),  stroke = FALSE, fillOpacity = 0.1, )

```
